{{ config(materialized='table') }}

-- Revenue and deal value analysis by acquisition channel (Olist).
-- Combines lead funnel with order revenue to estimate channel value.

with lead_channel_revenue as (
    select
        fl.acquisition_channel,
        fl.channel_id,
        count(fl.mql_id)                                        as total_leads,
        sum(case when fl.is_closed then 1 else 0 end)           as closed_deals,

        sum(fl.declared_monthly_revenue_brl)                    as total_declared_revenue_brl,
        avg(fl.declared_monthly_revenue_brl)                    as avg_declared_revenue_brl,

        -- Annual revenue potential = declared monthly * 12
        sum(fl.declared_monthly_revenue_brl) * 12               as annual_revenue_potential_brl
    from {{ ref('fact_leads') }} fl
    where fl.is_closed = true
    group by fl.acquisition_channel, fl.channel_id
),

orders_by_seller_channel as (
    -- Orders generated by sellers acquired via each channel
    select
        fl.acquisition_channel,
        count(distinct fo.order_id)                             as orders_from_channel,
        sum(fo.total_revenue_brl)                               as gmv_brl
    from {{ ref('fact_orders') }} fo
    join {{ ref('fact_leads') }} fl
        on fo.customer_id = fl.seller_id
    where fo.is_delivered = true
    group by fl.acquisition_channel
),

final as (
    select
        lcr.acquisition_channel,
        ch.channel_label,
        ch.channel_type,

        lcr.total_leads,
        lcr.closed_deals,
        round(100.0 * lcr.closed_deals / nullif(lcr.total_leads, 0), 2)    as conversion_rate_pct,

        round(coalesce(lcr.avg_declared_revenue_brl, 0), 2)                as avg_declared_monthly_rev_brl,
        round(coalesce(lcr.total_declared_revenue_brl, 0), 2)              as total_declared_monthly_rev_brl,
        round(coalesce(lcr.annual_revenue_potential_brl, 0), 2)            as annual_revenue_potential_brl,

        coalesce(os.orders_from_channel, 0)                                as orders_generated,
        round(coalesce(os.gmv_brl, 0), 2)                                  as gmv_brl

    from lead_channel_revenue lcr
    left join {{ ref('dim_channel') }} ch on lcr.channel_id = ch.channel_id
    left join orders_by_seller_channel os on lcr.acquisition_channel = os.acquisition_channel
)

select * from final
order by annual_revenue_potential_brl desc
